import { forwardRef } from "react";
import type { CardBlockId, CardDisplayOptions, CardLayout, UserSummary } from "@/lib/types";
import { DEFAULT_CARD_LAYOUT } from "@/lib/types";

import { AvatarBlock } from "./BusinessCardBlocks/AvatarBlock";
import { BioBlock } from "./BusinessCardBlocks/BioBlock";
import { StatsBlock } from "./BusinessCardBlocks/StatsBlock";
import { TopLanguagesBlock } from "./BusinessCardBlocks/TopLanguagesBlock";
import { TopReposBlock } from "./BusinessCardBlocks/TopReposBlock";


type Props = {
  summary: UserSummary;
  layout?: CardLayout;
  options?: CardDisplayOptions;
};

const BusinessCard = forwardRef<HTMLDivElement, Props>(({ summary, layout, options }, ref) => {
  const { profile, repositories, contributions, interests, activity } = summary;

  if (!profile) return null;

  const activeLayout = layout ?? DEFAULT_CARD_LAYOUT;


  const topLanguages = repositories?.languages.slice(0, 5) || [];
  const topTopics = repositories?.topics.slice(0, 10) || [];
  const reposToShow =
    profile.pinnedRepos.length > 0
      ? profile.pinnedRepos.slice(0, 2)
      : repositories?.topRepos.slice(0, 2) || [];

  const renderBlock = (blockId: CardBlockId) => {
    switch (blockId) {
      case "avatar":
        return <AvatarBlock profile={profile} />;
      case "bio":
        return <BioBlock profile={profile} options={options || {}} />;
      case "stats":
        return <StatsBlock profile={profile} contributions={contributions} options={options || {}} />;
      case "topLanguages":
        return (
          <TopLanguagesBlock
            topLanguages={topLanguages}
            topTopics={topTopics}
            interests={interests}
            activity={activity}
            options={options || {}}
          />
        );
      case "topRepos":
      default:
        return <TopReposBlock reposToShow={reposToShow} />;
    }
  };

  const fullBlocks = activeLayout.blocks.filter((block) => block.column === "full" && block.visible);
  const leftBlocks = activeLayout.blocks.filter((block) => block.column === "left" && block.visible);
  const rightBlocks = activeLayout.blocks.filter((block) => block.column === "right" && block.visible);

  return (
    <div
      ref={ref}
      data-testid="business-card-root"
      className="relative flex min-h-[630px] w-[1200px] flex-col overflow-hidden bg-gradient-to-br from-[#0d1117] to-[#161b22] p-16 font-sans text-white"
    >
      <div className="absolute -right-[10%] -top-[10%] h-[600px] w-[600px] rounded-full bg-accent/10 blur-[100px]" />
      <div className="absolute -bottom-[10%] -left-[10%] h-[500px] w-[500px] rounded-full bg-success/10 blur-[100px]" />

      <div className="z-10 flex flex-col gap-10">
        {fullBlocks.length > 0 && (
          <div className="space-y-8">
            {fullBlocks.map((block) => (
              <div key={block.id}>{renderBlock(block.id)}</div>
            ))}
          </div>
        )}

        <div className="flex gap-16">
          <div className="flex flex-1 flex-col space-y-8">
            {leftBlocks.map((block) => (
              <div key={block.id}>{renderBlock(block.id)}</div>
            ))}
          </div>
          <div className="flex w-[400px] flex-col space-y-8">
            {rightBlocks.map((block) => (
              <div key={block.id}>{renderBlock(block.id)}</div>
            ))}
          </div>
        </div>
      </div>

      <div className="z-10 mt-auto flex items-center justify-between border-t border-white/10 pt-6">
        <div className="text-lg text-gray-500">Generated by GitHub User Summary</div>
        <div className="font-mono text-lg text-gray-500">github-user-summary.vercel.app</div>
      </div>
    </div>
  );
});

BusinessCard.displayName = "BusinessCard";

export default BusinessCard;
